# Generated by Django 5.2 on 2025-04-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='last_completed_module',
        ),
    ]
