# Generated by Django 5.2 on 2025-04-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_remove_course_total_modules_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
