# Generated by Django 5.2 on 2025-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_slug_remove_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_limit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in hours'),
        ),
    ]
